### ISSUE TITLE
Mixing EE reads & writes slows down ingestion

### ISSUE THREAD

**Issue by alxmrs** [google/weather-tools#272]
Ingestion can be made faster if we don't mix reading assets with writing assets. 

https://github.com/google/weather-tools/blob/main/weather_mv/loader_pipeline/ee.py#L333

Let's explore implementation options for filtering out existing assets s.t. they don't make EE API calls. For example, let's check if COGs exist in a GCS bucket for the filter operation.

**Comment by deepgabani8** [comment]
Can we get a better explanation of the issue with EE?
Does it mean that we should avoid EE reads entirely in the pipeline OR we should separate EE reads and EE writes.

**Comment by deepgabani8** [comment]
The internal pipeline which arose the issue had a filter transform which was checking for assets in the EE and if not present, it would ingest asset in the same FilterFiles beam transform (since most of the COG files were already created and not ingested into EE by the previous pipeline which we had to stop).

So this pipeline was doing EE reads and EE writes in the same transform.

I now tried to separate EE reads and EE writes in separate transforms (as we do in the weather-tools. Mixing them was done just in the internal pipeline because it had already created COGs to consider.) separated by reshuffle.

This pipeline ingested around 2.384M COGs in 20hrs compared to the above pipeline's 4.454M in 46hrs under similar conditions - which is ~20% faster.

**Comment by deepgabani8** [comment]
POC on EE reads & writes issue
- When there is only ee writes in the entire pipeline:
The pipeline will just take source files' paths as an input and ingest them into earth engine without any filtering step. It took 1hr17min to finish this pipeline.
- When ee reads & ee writes are in separate transforms:
The pipeline does filtering step in a separate transform (as it does in the weather-tools) before converting step. This way all ee reads happen all together and then conversion & ingestion happens where all ee writes happen all together. This pipeline took 1hr26min (8min taken by the filter transform which is not in the above pipeline) to finish.
- When ee reads & ee writes happen together:
The pipeline has the logic to check ee asset presence (ee read) and if the asset is not present, it will read the tiff file and ingest (ee write) in the same transform. This way ee reads and ee writes happen together in the same transform. This pipeline took 1hr55min to finish.

**Comment by deepgabani8** [comment]
Conclusion
From the above experiments, it is observable that mixing EE reads & writes does make the ingestion slow comparatively. Though, weather-mv is doing EE reads and EE writes in separate transforms.

Closing this.

**Comment by alxmrs** [comment]
Thanks for following up with this, Deep.
